[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake", "nodejs_20"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm rebuild better-sqlite3"]

[start]
cmd = "node start.js"
